# Generates public/index.html and public/assets/techo.css from the design source.
import re,os,sys,json
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
S=os.path.join(root,'src-build','design')+'/'
src=open(S+'techo.html',encoding='utf-8').read()
L=src.split('\n')
# ---- CSS
style='\n'.join(L[5:98])   # :root .. a.ln  (no <style> tags)
drop=[r'^\.stage\{',r'^\.book\{',r'^/\* -+ spread',r'^\.spread',r'^@keyframes turn',r'^@media \(prefers-reduced-motion:reduce\)\{\.spread',r'^/\* stack mode',r'^\.stack ',r'^\.nav\{',r'^body\{']
style='\n'.join(l for l in style.split('\n') if not any(re.match(p,l) for p in drop))
extra=open(S+'extra.css',encoding='utf-8').read()
jp=extra[extra.index('/* ---------- generic journal page'):extra.index('/* ---------- admin')]
css=('/* Techo — generated by src-build/build.py; edit the sources there. */\n'+style+'\n:root{--mono:"JetBrains Mono",ui-monospace,"SF Mono",Menlo,Consolas,monospace}\n'+'\n'+jp+
     open(os.path.join(root,'src-build/book-extra.css'),encoding='utf-8').read()+
     '\n[hidden]{display:none!important}\n#static{position:absolute;left:-99999px;top:0;width:530px}\n')
os.makedirs(os.path.join(root,'public/assets'),exist_ok=True)
open(os.path.join(root,'public/assets/techo.css'),'w',encoding='utf-8').write(css)
# ---- symbols
a=src.index('<svg width="0" height="0"');b=src.index('</svg>',src.index('</defs>'))+6
symbols=src[a:b]
# ---- static pages
def cal_html(y,mo,today):
    import datetime
    first=datetime.date(y,mo,1).weekday()  # Mon=0
    n=(datetime.date(y+(mo==12),mo%12+1,1)-datetime.date(y,mo,1)).days
    out=['<div class="cal" aria-hidden="true">']+['<span class="h">%s</span>'%c for c in '一二三四五六日']
    out+=['<span></span>']*first
    out+=['<span%s>%d</span>'%(' class="t"' if d==today else '',d) for d in range(1,n+1)]
    return ''.join(out)+'</div>'
pages=[]
for m in re.finditer(r'<section class="spread[^"]*" data-label="([^"]+)"[^>]*>(.*?)</section>',src,re.S):
    label=m.group(1).split('–')[0].strip()
    body=m.group(2)
    li=body.index('<div class="page l">');ri=body.index('<div class="page r">')
    left=body[li:ri].rstrip();right=body[ri:].rstrip()
    left=left.replace('<div class="page l">','<div class="page l day" data-label="%s">'%label,1)
    right=right.replace('<div class="page r">','<div class="page r day">',1)
    pages+=[left,right]
assert len(pages)==6,len(pages)
html='\n'.join('  '+p for p in pages)
html=html.replace('<div class="cal" id="cal" aria-hidden="true"></div>',cal_html(2026,9,25))
html=html.replace('<a class="ln hand s" href="https://github.com/"','<a id="gh" class="ln hand s" href="https://github.com/"')
assert 'id="gh"' in html and 'id="mail"' in html and 'class="cal"' in html
tpl=open(os.path.join(root,'src-build/index.tpl.html'),encoding='utf-8').read()
out=tpl.replace('<!--SYMBOLS-->',symbols).replace('<!--STATIC_PAGES-->',html)
inline=sys.argv[1] if len(sys.argv)>1 else None
out=out.replace('<!--INLINE_DATA-->','')
open(os.path.join(root,'public/index.html'),'w',encoding='utf-8').write(out)
adm=open(os.path.join(root,'src-build/admin.tpl.html'),encoding='utf-8').read().replace('<!--SYMBOLS-->',symbols)
os.makedirs(os.path.join(root,'public/admin'),exist_ok=True)
open(os.path.join(root,'public/admin/index.html'),'w',encoding='utf-8').write(adm)
print('ok',len(out),len(css))
